#!/usr/bin/env lua

-- extract-code.lua
-- Extracts Lua code blocks from markdown files
-- Usage: lua scripts/extract-code.lua [directories...]
--
-- Creates extracted/ directory with individual .lua files

local fs = require "lfs" or nil

-- Configuration
local OUTPUT_DIR = "extracted"

-- Get directories to process
local directories = { ... }
if #directories == 0 then
  directories = { "en", "zh" }
end

-- Statistics
local stats = {
  files_processed = 0,
  blocks_extracted = 0,
}

-- Create output directory
local function ensure_output_dir(base)
  local path = base .. "/" .. OUTPUT_DIR
  fs.mkdir(path)
  return path
end

-- Extract code blocks from markdown content
local function extract_code_blocks(content, output_path, source_file)
  local in_code = false
  local current_block = nil
  local block_count = 0
  
  for line in content:gmatch("[^\n]*\n?") do
    -- Check for code block start
    local lang = line:match("^```(%w*)")
    if lang and not in_code then
      in_code = true
      block_count = block_count + 1
      current_block = {
        lang = lang,
        lines = {},
        source = source_file,
        block_num = block_count,
      }
    elseif line:match("^```%s*$") and in_code then
      -- End of code block
      in_code = false
      
      -- Only write Lua blocks
      if current_block and current_block.lang == "lua" then
        local code = table.concat(current_block.lines, "\n")
        
        -- Skip empty blocks or obvious fragments
        if #code > 0 and not code:match("<FILL>") and not code:match("%.%.%.") then
          local filename = string.format("%s_block_%03d.lua", 
            source_file:gsub("[/\\]", "_"), 
            current_block.block_num)
          
          local filepath = output_path .. "/" .. filename
          local out = io.open(filepath, "w")
          if out then
            -- Add header comment
            out:write(string.format("-- Extracted from: %s (block %d)\n", 
              current_block.source, 
              current_block.block_num))
            out:write("-- Auto-generated by extract-code.lua\n\n")
            out:write(code)
            out:write("\n")
            out:close()
            stats.blocks_extracted = stats.blocks_extracted + 1
          end
        end
      end
      
      current_block = nil
    elseif in_code and current_block then
      table.insert(current_block.lines, line)
    end
  end
  
  return block_count
end

-- Process a single markdown file
local function process_file(filepath, output_dir)
  local file = io.open(filepath, "r")
  if not file then
    print(string.format("  ERROR: Cannot open %s", filepath))
    return
  end
  
  local content = file:read("*all")
  file:close()
  
  extract_code_blocks(content, output_dir, filepath)
  stats.files_processed = stats.files_processed + 1
end

-- Get list of markdown files in directory
local function get_markdown_files(dir)
  local files = {}
  
  for entry in fs.dir(dir) do
    if entry:match("%.md$") then
      table.insert(files, dir .. "/" .. entry)
    end
  end
  
  table.sort(files)
  return files
end

-- Main execution
print("lua-journey Code Extractor")
print("==========================")
print()

for _, dir in ipairs(directories) do
  if not fs.attributes(dir, "type") then
    print(string.format("Directory not found: %s", dir))
    goto continue
  end
  
  print(string.format("Processing %s/...", dir))
  
  local output_dir = ensure_output_dir(dir)
  local files = get_markdown_files(dir)
  
  for _, filepath in ipairs(files) do
    print("  " .. filepath)
    process_file(filepath, output_dir)
  end
  
  ::continue::
end

-- Print summary
print()
print("Summary")
print("-------")
print(string.format("Files processed:    %d", stats.files_processed))
print(string.format("Code blocks found: %d", stats.blocks_extracted))
print()
print(string.format("Output directory:   %s/*/extracted/", os.getcwd()))
print()
print("Extraction complete")
